[2025-08-07 11:50:38,804] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-07T11:48:37.190902+00:00 [queued]>
[2025-08-07 11:50:38,820] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-07T11:48:37.190902+00:00 [queued]>
[2025-08-07 11:50:38,821] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-07 11:50:38,821] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-07 11:50:38,821] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-07 11:50:38,843] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): fetch_and_send_weather> on 2025-08-07 11:48:37.190902+00:00
[2025-08-07 11:50:38,853] {standard_task_runner.py:52} INFO - Started process 13218 to run task
[2025-08-07 11:50:38,860] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'fetch_and_send_weather', 'scheduled__2025-08-07T11:48:37.190902+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpfy0ml3jy', '--error-file', '/tmp/tmpqoikllul']
[2025-08-07 11:50:38,862] {standard_task_runner.py:80} INFO - Job 292: Subtask fetch_and_send_weather
[2025-08-07 11:50:38,983] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-07T11:48:37.190902+00:00 [running]> on host 40571d888a39
[2025-08-07 11:50:39,344] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alla
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=fetch_and_send_weather
AIRFLOW_CTX_EXECUTION_DATE=2025-08-07T11:48:37.190902+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-07T11:48:37.190902+00:00
[2025-08-07 11:50:39,346] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-07 11:50:39,346] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts && python3 kafka/producer.py']
[2025-08-07 11:50:39,370] {subprocess.py:85} INFO - Output:
[2025-08-07 11:50:44,054] {subprocess.py:92} INFO - Erreur d'appel API: 429
[2025-08-07 11:50:44,054] {subprocess.py:92} INFO - Aucune donnée météo récupérée.
[2025-08-07 11:50:44,164] {subprocess.py:96} INFO - Command exited with return code 0
[2025-08-07 11:50:44,250] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=fetch_and_send_weather, execution_date=20250807T114837, start_date=20250807T115038, end_date=20250807T115044
[2025-08-07 11:50:44,294] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-07 11:50:44,360] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
