[2025-08-07 03:34:38,493] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-08-07T03:32:32.812401+00:00 [queued]>
[2025-08-07 03:34:38,506] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-08-07T03:32:32.812401+00:00 [queued]>
[2025-08-07 03:34:38,507] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-07 03:34:38,507] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-07 03:34:38,507] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-07 03:34:38,525] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): verify_pipeline> on 2025-08-07 03:32:32.812401+00:00
[2025-08-07 03:34:38,531] {standard_task_runner.py:52} INFO - Started process 3006 to run task
[2025-08-07 03:34:38,534] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'verify_pipeline', 'scheduled__2025-08-07T03:32:32.812401+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpo_0kizb4', '--error-file', '/tmp/tmpvui24oqs']
[2025-08-07 03:34:38,536] {standard_task_runner.py:80} INFO - Job 88: Subtask verify_pipeline
[2025-08-07 03:34:38,655] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-08-07T03:32:32.812401+00:00 [running]> on host 47565329e35b
[2025-08-07 03:34:38,949] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alla
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=verify_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2025-08-07T03:32:32.812401+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-07T03:32:32.812401+00:00
[2025-08-07 03:34:38,950] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-07 03:34:38,950] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            echo "⏳ Attente traitement Logstash..." && sleep 30 &&\n            curl -s "http://elasticsearch:9200/_cat/indices/weather*" || echo "Pas encore d\'index weather"\n        ']
[2025-08-07 03:34:38,967] {subprocess.py:85} INFO - Output:
[2025-08-07 03:34:38,969] {subprocess.py:92} INFO - ⏳ Attente traitement Logstash...
[2025-08-07 03:35:09,002] {subprocess.py:96} INFO - Command exited with return code 0
[2025-08-07 03:35:09,061] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=verify_pipeline, execution_date=20250807T033232, start_date=20250807T033438, end_date=20250807T033509
[2025-08-07 03:35:09,102] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-08-07 03:35:09,108] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 3006. PIDs of all processes in the group: [3006]
[2025-08-07 03:35:09,108] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 3006
[2025-08-07 03:35:09,110] {process_utils.py:75} INFO - Process psutil.Process(pid=3006, status='terminated', exitcode=0, started='03:34:37') (3006) terminated with exit code 0
