[2025-08-06 20:36:51,043] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-06T18:36:44.255517+00:00 [queued]>
[2025-08-06 20:36:51,054] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-06T18:36:44.255517+00:00 [queued]>
[2025-08-06 20:36:51,054] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-06 20:36:51,054] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-06 20:36:51,054] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-06 20:36:51,070] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): fetch_and_send_weather> on 2025-08-06 18:36:44.255517+00:00
[2025-08-06 20:36:51,076] {standard_task_runner.py:52} INFO - Started process 555 to run task
[2025-08-06 20:36:51,081] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'fetch_and_send_weather', 'scheduled__2025-08-06T18:36:44.255517+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpl08ba8bv', '--error-file', '/tmp/tmpqfkiwp47']
[2025-08-06 20:36:51,083] {standard_task_runner.py:80} INFO - Job 2: Subtask fetch_and_send_weather
[2025-08-06 20:36:51,161] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-06T18:36:44.255517+00:00 [running]> on host cade4da63509
[2025-08-06 20:36:51,388] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=fetch_and_send_weather
AIRFLOW_CTX_EXECUTION_DATE=2025-08-06T18:36:44.255517+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-06T18:36:44.255517+00:00
[2025-08-06 20:36:51,388] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-06 20:36:51,389] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts && python3 kafka/producer.py']
[2025-08-06 20:36:51,406] {subprocess.py:85} INFO - Output:
[2025-08-06 20:36:56,582] {subprocess.py:92} INFO - Envoi vers Kafka : {'temperature': 29, 'humidity': 79, 'windSpeed': 4.1, 'cloudCover': 100, 'rainIntensity': 0, 'timestamp': '2025-08-06T20:36:00Z'}
[2025-08-06 20:36:56,705] {subprocess.py:96} INFO - Command exited with return code 0
[2025-08-06 20:36:56,783] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=fetch_and_send_weather, execution_date=20250806T183644, start_date=20250806T203651, end_date=20250806T203656
[2025-08-06 20:36:56,842] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-06 20:36:56,896] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
