[2025-08-07 11:13:51,936] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-07T11:11:41.830671+00:00 [queued]>
[2025-08-07 11:13:51,955] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-07T11:11:41.830671+00:00 [queued]>
[2025-08-07 11:13:51,955] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-07 11:13:51,955] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-07 11:13:51,956] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-07 11:13:51,979] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): fetch_and_send_weather> on 2025-08-07 11:11:41.830671+00:00
[2025-08-07 11:13:51,989] {standard_task_runner.py:52} INFO - Started process 1608 to run task
[2025-08-07 11:13:51,994] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'fetch_and_send_weather', 'scheduled__2025-08-07T11:11:41.830671+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmp87jgyll0', '--error-file', '/tmp/tmp61meqscv']
[2025-08-07 11:13:51,995] {standard_task_runner.py:80} INFO - Job 69: Subtask fetch_and_send_weather
[2025-08-07 11:13:52,088] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-07T11:11:41.830671+00:00 [running]> on host b22dcc1493a4
[2025-08-07 11:13:52,383] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alla
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=fetch_and_send_weather
AIRFLOW_CTX_EXECUTION_DATE=2025-08-07T11:11:41.830671+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-07T11:11:41.830671+00:00
[2025-08-07 11:13:52,384] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-07 11:13:52,385] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts && python3 kafka/producer.py']
[2025-08-07 11:13:52,410] {subprocess.py:85} INFO - Output:
[2025-08-07 11:13:56,854] {subprocess.py:92} INFO - Envoi vers Kafka : {'temperature': 28.9, 'humidity': 76, 'windSpeed': 5.4, 'cloudCover': 49, 'rainIntensity': 0, 'timestamp': '2025-08-07T11:13:00Z'}
[2025-08-07 11:13:56,987] {subprocess.py:96} INFO - Command exited with return code 0
[2025-08-07 11:13:57,065] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=fetch_and_send_weather, execution_date=20250807T111141, start_date=20250807T111351, end_date=20250807T111357
[2025-08-07 11:13:57,107] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-08-07 11:13:57,113] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 1608. PIDs of all processes in the group: [1608]
[2025-08-07 11:13:57,113] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 1608
[2025-08-07 11:13:57,114] {process_utils.py:75} INFO - Process psutil.Process(pid=1608, status='terminated', exitcode=0, started='11:13:51') (1608) terminated with exit code 0
