[2025-08-06 20:01:16,061] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-06T18:01:13.035441+00:00 [queued]>
[2025-08-06 20:01:16,075] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-06T18:01:13.035441+00:00 [queued]>
[2025-08-06 20:01:16,076] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-06 20:01:16,076] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-06 20:01:16,076] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-06 20:01:16,110] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): fetch_and_send_weather> on 2025-08-06 18:01:13.035441+00:00
[2025-08-06 20:01:16,120] {standard_task_runner.py:52} INFO - Started process 490 to run task
[2025-08-06 20:01:16,126] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'fetch_and_send_weather', 'scheduled__2025-08-06T18:01:13.035441+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpimjekhe6', '--error-file', '/tmp/tmp332uljdd']
[2025-08-06 20:01:16,128] {standard_task_runner.py:80} INFO - Job 2: Subtask fetch_and_send_weather
[2025-08-06 20:01:16,257] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-06T18:01:13.035441+00:00 [running]> on host e549a7900e51
[2025-08-06 20:01:16,613] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=fetch_and_send_weather
AIRFLOW_CTX_EXECUTION_DATE=2025-08-06T18:01:13.035441+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-06T18:01:13.035441+00:00
[2025-08-06 20:01:16,614] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-06 20:01:16,615] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts && python3 kafka/producer.py']
[2025-08-06 20:01:16,638] {subprocess.py:85} INFO - Output:
[2025-08-06 20:01:22,010] {subprocess.py:92} INFO - Envoi vers Kafka : {'temperature': 29, 'humidity': 74, 'windSpeed': 3.1, 'cloudCover': 96, 'rainIntensity': 0, 'timestamp': '2025-08-06T20:01:00Z'}
[2025-08-06 20:01:22,147] {subprocess.py:96} INFO - Command exited with return code 0
[2025-08-06 20:01:22,228] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=fetch_and_send_weather, execution_date=20250806T180113, start_date=20250806T200116, end_date=20250806T200122
[2025-08-06 20:01:22,311] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-06 20:01:22,599] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
